Description: RDS PostgreSQL + S3 bucket (without VpcSecurityGroupIds to bypass EarlyValidation)

Parameters:
  DBSubnetIds:
    Type: CommaDelimitedList
    Description: List of at least 2 subnet IDs for the DB subnet group

  DBUsername:
    Type: String
    NoEcho: true
    Description: Master username for RDS database
    MinLength: 1
    MaxLength: 63

  DBPassword:
    Type: String
    NoEcho: true
    Description: Master password for RDS database
    MinLength: 8
    MaxLength: 128

  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
    Description: RDS instance type

  Environment:
    Type: String
    Default: lab
    Description: Environment name for tagging

Resources:
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: reports-bucket

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Lab PostgreSQL database
      SubnetIds: !Ref DBSubnetIds
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: lab-postgres-subnet-group

  LabPostgres:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: postgres
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      StorageType: gp2
      PubliclyAccessible: true
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 0
      DeletionProtection: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: lab-postgres-db

Outputs:
  BucketName:
    Description: Name of the S3 reports bucket
    Value: !Ref ReportsBucket

  RDSEndpoint:
    Description: PostgreSQL RDS endpoint address
    Value: !GetAtt LabPostgres.Endpoint.Address

  RDSPort:
    Description: PostgreSQL RDS port
    Value: !GetAtt LabPostgres.Endpoint.Port

  DBInstanceIdentifier:
    Description: RDS database instance identifier
    Value: !Ref LabPostgres
